// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmallUrlShortener.Data;

namespace SmallUrlShortener.Migrations
{
    [DbContext(typeof(ShortenerContext))]
    [Migration("20210526153013_AddedIndices")]
    partial class AddedIndices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("SmallUrlShortener.Data.UrlMapping", b =>
                {
                    b.Property<int>("URLMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortLink")
                        .HasColumnType("TEXT");

                    b.HasKey("URLMappingId");

                    b.HasIndex("DirectLink", "ShortLink");

                    b.ToTable("UrlMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
