// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmallUrlShortener.Data;

namespace SmallUrlShortener.Migrations
{
    [DbContext(typeof(ShortenerContext))]
    partial class ShortenerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("SmallUrlShortener.Data.UrlMapping", b =>
                {
                    b.Property<int>("URLMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortLinkId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("URLMappingId");

                    b.HasIndex("OriginalLink")
                        .IsUnique();

                    b.HasIndex("ShortLinkId")
                        .IsUnique();

                    b.ToTable("UrlMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
